"""
Django settings for X project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '00k55vv!-$nv#+na22p6d)!hmjk_3_th27!u7+)jicq@$qy&q^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Buyer',
    'Seller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'X.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'X.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(os.path.join(BASE_DIR,'static'),)

# STATIC_ROOT = os.path.join(BASE_DIR,'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')


#阿里支付
alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2LgKldFqC/nAnnan0W6x9c/Wzmvc9Q6OsZs7G1KLqOCk60/tvX8VQ5U/ysvweMXNLAmuwDxVbvmboQ+gzSZ3eD/ovgXsVXvNeuHNYiNeFux/Zn6wC3uv3yZjJB+QvKfZzFz9IUK3mbL0rvfuwgaWhDNuxCpZn+Z6ei/ikfE8hdoye/h+lDmx5yXaaGG6JLClDBXlhQh2z34OM8+6AaR+4agYzyBORIXzokxwY7eBBL6ysAPwhRj0Qzr0DV1zplPJqhBCFnq7TQQYr5LvrugQDEdq88tQG3pLI/4pfeovMPmBabGmD/+fUo5FHtpNhBclruHqRgkV0KMjwqnwKkJ4wwIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key_string ="""-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEA2LgKldFqC/nAnnan0W6x9c/Wzmvc9Q6OsZs7G1KLqOCk60/tvX8VQ5U/ysvweMXNLAmuwDxVbvmboQ+gzSZ3eD/ovgXsVXvNeuHNYiNeFux/Zn6wC3uv3yZjJB+QvKfZzFz9IUK3mbL0rvfuwgaWhDNuxCpZn+Z6ei/ikfE8hdoye/h+lDmx5yXaaGG6JLClDBXlhQh2z34OM8+6AaR+4agYzyBORIXzokxwY7eBBL6ysAPwhRj0Qzr0DV1zplPJqhBCFnq7TQQYr5LvrugQDEdq88tQG3pLI/4pfeovMPmBabGmD/+fUo5FHtpNhBclruHqRgkV0KMjwqnwKkJ4wwIDAQABAoIBAQCYpjm+gX0i5k6Iz6cxW7k6HaV+THecnR5hd6fQfPomf+VqYihhO6xsqCoA3FmLmDgGduOCQH0k5+h5MBrhpeCs8MctYdqv874uefJC2AqkNv0d4sp5rCubENzwStOWLty4mB8sWGQefPDgdX7VZ/KJN/kjb3klqiBHBIegqL0qwdQNmnQl06UtLE60eDaCGx0R+XFpWZGCeJqZNZmsUjH8yk9u7TJNlZPezJUQo8xNzbCgapw9beNaW8JeZGAqhkzlaG+HCbbwDhUJ3IbpS5Xxp/qR0ddPPNC95YTBdx+GnjxEUS2uM9/yeicqjNNQ5BYlbfwVwO/Iw/jsmD6o33KBAoGBAPwAv4xg7TFaR59amsJdYEvnePpMd4PeEXHIzGblzPrZfoGtvV5UmiBjDS3OEHAFwYy2oH4bCo9AV1RpV+mH+t5ObVH8viiop3G8xdbH31eF5VLHwAb8uz62QYvq8rtmqoFNVpckzU33ivdra1cDgYOo6IfLjJVEOWBbpfsLuLvjAoGBANwoBfMH2uYTf3/7fljkkzNTlQObQ037GGY82X6CfkXZIiWUxxMPKo+e8OOiuXvixb6aG1DrCX+6oj870GXM5pqR696cw2IQJ0CQdNPtHAB3wQviSL9tAZ58rOgRw4zeimPMBiGzKleexQFYEBDbYb3gX6ky0b3uB5hjDKKVCaWhAoGAaOG21yoQDhZQ8NW4y2Qpi+3Ov/3LUCrAf+bei4ThBxY2PKqewf/cFdajyYiV9smugG4R5epDPtO8hPlDCYL6ukNR5GmYizuGVSQIAxg0sCyeARH5re7Jz5PzO9SRKcXU+PPDMiyy9dwtDkS67AAdizplbP8eh5FZf+0k65M5U5kCgYA0zDBpEVgw1zo7ki/B18dphsD05XZlrDM0yaELUvY/gAxNYPnBG2EEooR4wxyilkcAJ+snI8baaALjEVAwKcygAyDC+WtuCBuxwzMRZArUHeQhGnqB1f2Oaa351dDE5tXfix1pVZNxAfWTFfB8anBtXfLzG+nrF7ugkxiDoSR4IQKBgDEMj2IYmPwKJr+J1cPbRuC5fwCh7uB6etF2w8HE0nSmgdYifiOdF23AOS4pTo/g72wP9esOtY+6/5nC1V7HMuH1xmagetSon7lR7mHn8DodLVQMFyWkImTI/I6ldLKipr0HWhm6+WtnxXWcN4jpavWbsSaM+WaOLHvSc+ScrFiw
-----END RSA PRIVATE KEY-----"""
